name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installer les dépendances
      run: pip install pytest

    - name: Exécuter les tests
      run: pytest test_calculator.py