name: Exécution des tests unitaires

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installer les dépendances
      run: pip install -r requirements.txt

    - name: Exécuter les tests
      run: pytest
